variables:
  IMAGE_PATH: $DOCKER_REGISTRY/$CI_PROJECT_NAME
  TESTS_UNIT_DISABLED: "true"
  TESTS_COVERAGE_DISABLED: "true"

stages:
  - test
  - build
  - deploy
  - release

include:
  - project: 'x.la/contracts/shared-ci-library'
    ref: main
    file:
      - 'jobs/tests.gitlab-ci.yaml'

.before_script:
  before_script:
    - |
      if [[ "$CI_COMMIT_TAG" == "" ]]; then
        export IMAGE_TAG="$CI_COMMIT_REF_SLUG-$CI_ENVIRONMENT_NAME"
      else
        export IMAGE_TAG="$CI_COMMIT_TAG-$CI_ENVIRONMENT_NAME"
      fi
    - echo "DOCKER REGISTRY IMAGE >> $IMAGE_PATH:$IMAGE_TAG"

.deploy_scripts:
  stage: deploy
  image: $DEPLOY_IMAGE
  extends: .before_script
  script:
    - aws --region $AWS_DEFAULT_REGION eks update-kubeconfig --name $EKS_CLUSTER_NAME
    - cd /deploy
    - echo "Helm args >> ${HELM_ARGS}"
    - helm dependency update $CI_PROJECT_NAME
    - helm upgrade --install ${CI_PROJECT_NAME} -n ${CI_ENVIRONMENT_NAME}
      --values ${CI_PROJECT_NAME}/values-${CI_ENVIRONMENT_NAME}.yaml
      --set theone.image.tag=${IMAGE_TAG}
      --set theone.image.repository=${IMAGE_PATH}
      --set theone.env.GITHASH=${CI_COMMIT_SHA}
      ${CI_PROJECT_NAME}
      ${HELM_ARGS}
  when: manual
  tags: ["deploy"]

.build_scripts:
  stage: build
  image: docker:latest
  extends: .before_script
  services:
    - docker:dind
  script:
    - apk add -q --no-cache python3 py3-pip git
    - pip3 install -q --no-cache-dir awscli
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_PATH
    - env | grep XLA | cut -c 5- > env/.env.gitlab
    - docker build
      --tag "$IMAGE_PATH:$IMAGE_TAG"
      --file Dockerfile .
    - docker push "$IMAGE_PATH:$IMAGE_TAG"
    - echo "DOCKER REGISTRY IMAGE >> $IMAGE_PATH:$IMAGE_TAG"
  tags: ["build"]

build:dev:
  extends: .build_scripts
  environment:
    name: dev

build:uat:
  extends: .build_scripts
  environment:
    name: uat
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'

build:prod:
  extends: .build_scripts
  environment:
    name: core
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'

deploy:dev:
  extends: .deploy_scripts
  environment:
    name: dev

deploy:uat:
  extends: .deploy_scripts
  environment:
    name: uat
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'

deploy:prod:
  extends: .deploy_scripts
  environment:
    name: core
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
  needs: ["deploy:uat"]
