export enum TagType {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  PRIVATE = 'PRIVATE',
  COMMUNITY = 'COMMUNITY',
  DISTRIBUTOR = 'DISTRIBUTOR',
  RECIPIENT = 'recipient',
  PENDING = 'PENDING',
}
