export const ToastDescriptionType = {
    SIMPLE: 'SIMPLE',
    DRAFT_CREATED: 'DRAFT_CREATED',
    DRAFT_CHANGED: 'DRAFT_CHANGED',
    CONTRACT_PUBLISHED: 'CONTRACT_PUBLISHED',
    CONTRACT_UPDATED: 'CONTRACT_UPDATED',
};
